# Generated by Django 4.2.4 on 2023-08-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='direccion',
            new_name='apellido',
        ),
    ]
